import OSLog
import Foundation

/// Central logging utility for the CBT app.
///
/// ### Privacy Policy
/// This app follows a strict privacy-first logging policy:
/// 1. **User Data**: Any data generated by the user (notes, thoughts, specific intensities, mood raw values, UUIDs)
///    MUST be logged using the `privacy: .private` modifier.
/// 2. **System Events**: Lifecycle events, navigation, and state changes (e.g., "View Appeared", "Tab Selected")
///    SHOULD be logged using `privacy: .public` to aid in production triage.
/// 3. **Errors**: Error descriptions should generally be `.private` if they contain path metadata or user context.
enum AppLogger {
    private static let subsystem = Bundle.main.bundleIdentifier ?? "com.meliapps.CBT"

    /// Standard factory for creating loggers.
    /// - Parameter category: A descriptive name for the subsystem area (e.g., "Data", "Security", "UI")
    nonisolated static func make(category: String) -> Logger {
        Logger(
            subsystem: subsystem,
            category: category
        )
    }
}
